// Autogenerated by generate_platform_h.py and not yet checked by a human

/*
  This file is auto converted. And possibly manually edited, from platformio.ini so that it can be included by those using Arduino.ini
*/

#ifndef PLATFORM_H
#define PLATFORM_H

// PlatformIO Project Configuration File - Frugal-IoT OSPIT irrigation node
//
// Two boards, deliberately, for the same application:
//
//   ff_openmppt  the FF-ESP32-OpenMPPT solar charge controller OSPIT itself runs on. This is the
//                target board; MPPT is NOT implemented here (that is P4/P5) - the charge control
//                hardware is simply left alone and this build uses the board only for irrigation.
//   s2_mini      a Lolin S2 Mini, i.e. the same application on a plain dev board with no MPPT
//                hardware at all. More pins, less to go wrong, and it proves nothing in the
//                application depends on the charge controller.
//
// They target different ARDUINO_* macros (ARDUINO_ESP32_DEV and ARDUINO_LOLIN_S2_MINI), so
// scripts/generate_platform_h.py emits both into platform.h rather than marking one DISABLED -
// unlike two envs for the same board, where it keeps only the first.

// [platformio]
// Anything matching *-local.ini is loaded on top of this file, and is never committed. Two of them,
// for two different jobs - see build_flags_secrets below:
//   platformio-local.ini          your own overrides: the local library (see "Building against a
//                                 local library" in CLAUDE.md) and debug flags. Never reaches a
//                                 release build.
//   platformio-secrets-local.ini  the enrolment secret, and which server this build is for.
//                                 scripts/release.zsh --build hands it to the release build.
// A GLOB rather than names, so a fresh clone with neither builds unchanged.
// extra_configs = *-local.ini
// name: Frugal-IoT Irrigation
// description: Solar-powered sequenced soil-moisture irrigation
// src_dir = .
// src_dir = . keeps the sketch at the top of the repo, which is what lets the SAME directory build
// in the Arduino IDE: it needs a .ino whose name matches the folder, beside its own .cpp/.h files.
// Arduino ignores every subdirectory except src/, so lib/, data/, scripts/ and .pio/ are invisible
// to it.

// [common]
// A developer working on the library at the same time drops a symlink at lib/Frugal-IoT (it is
// gitignored) - PlatformIO searches the project's own lib/ before lib_deps, so the symlink wins
// and edits to the library are picked up with no reinstall.
// Arduino IDE users install Frugal-IoT from the Library Manager instead.
// lib_deps =
//     Frugal-IoT@^2.0.4
    // ModbusMaster (the RS485 soil probes) is a declared dependency of Frugal-IoT, so
    // lib_ldf_mode = chain pulls it in - it does not need listing here.

// lib_deps_oled =
//     ${common.lib_deps}
//     adafruit/Adafruit SSD1306@^2.5.0
//     adafruit/Adafruit GFX Library@^1.10.13

// These are flags common to pretty much all frugal-iot projects
// comment or uncomment debug flags based on need
// build_flags_frugaliot =
// #define CONTROL_IRRIGATION_DEBUG
// #define SENSOR_SOILMODBUS_DEBUG
// #define SYSTEM_MODBUS_DEBUG
// #define SENSOR_ANALOG_DEBUG
    // On for the sleep-test branch: it is what prints `Sleeping` just before the board goes, which
    // is the only indication a tester with a serial monitor gets.
// #define SYSTEM_POWER_DEBUG
// #define SYSTEM_TIME_DEBUG
// #define SYSTEM_MQTT_DEBUG
// #define SYSTEM_WIFI_DEBUG
// #define SYSTEM_CAPTIVE_DEBUG // Heap, page,size, client disconnect tracing. 
// #define SYSTEM_CAPTIVE_MINIMAL // replace portal with one-line page to tell transfort fault from content.
// #define SYSTEM_GROUP_HEAP_DEBUG // free heap & largest contiguous block check after each module setup/loop
#define SYSTEM_LITTLEFS_SUPPORTDEPRECATED // one-shot migration of saved config from /<id>/<leaf> dirs to flat /<id>.<leaf> files
// #define SYSTEM_WIFI_DEBUG
// #define SYSTEM_MESSAGE_DEBUG
    // Turn off C++ exceptions - nothing in this example throws. See examples/agri/platformio.ini
    // for the measurements behind this.
//     -fno-exceptions

// Filled in by the *-local.ini files, which are never committed. Empty here, so this file can be
// committed and a checkout without them still builds. Two keys rather than one because a value set
// in a *-local.ini REPLACES the one here rather than adding to it, so each file needs its own:
//   build_flags_secrets - platformio-secrets-local.ini: the enrolment secret, and which server
//                         this build is for. ota_build.py --secrets links it into a release build.
//   build_flags_local   - platformio-local.ini: your own debug flags. Never reaches an OTA build.
// build_flags_secrets =
// build_flags_local =

// flags that apply only in main (the library can see them, but doesnt need them)
// build_flags_main =
//     ${common.build_flags_secrets}
//     ${common.build_flags_local}

// project specific flags that are needed by the library
// build_flags_library =
#define SYSTEM_OTA_PREFIX "irrigation"

// Battery interlock thresholds, in millivolts. Each is a LIMIT with a DEAD BAND: 12100 +/- 200
// means "off below 11.9V, on again above 12.3V". Here rather than in the sketch because they are
// the main thing that differs between installations - battery chemistry, panel size, and how much
// you mind losing each thing. Together they set the ORDER things are given up in as the battery
// falls: USB first, then irrigation, and the router last. See the note in the .ino.
// build_flags_lvd =
#define IRRIGATION_LVD_LOAD_MV 12100
#define IRRIGATION_LVD_LOAD_HYST_MV 200
#define IRRIGATION_LVD_USB_MV 13100
#define IRRIGATION_LVD_USB_HYST_MV 300
#define IRRIGATION_LVD_IRRIGATION_MV 12600
#define IRRIGATION_LVD_IRRIGATION_HYST_MV 200
#define SENSOR_BATTERY_MIN 10000 // Lead Acid battery (for display and graphing)
#define SENSOR_BATTERY_MAX 15000 // Lead Acid battery (for display and graphing)

// Ask the linker for a map file - scripts/size_report.py reads it.
// build_flags_map =
//     -Wl,-Map=$BUILD_DIR/firmware.map

// AsyncTCP's service task stack, which is HEAP, not static - so it does not show up in the RAM
// figure at the end of a build, and that is why it went unnoticed.
//
// The library defaults it to 8192*2, sixteen kilobytes, which is the same size as one of mbedTLS's
// two TLS record buffers. The captive portal's handlers are a form POST, a status page and a couple
// of redirects - nothing that needs half of that. On an S2, where TinyUSB has already taken 23KB
// of internal RAM, those sixteen kilobytes are the difference between a TLS handshake that fits and
// one that returns "SSL - Memory allocation failed".
//
// #define works
// not an sdkconfig setting.
//
// 8192 moved an S2 from "cannot allocate the record buffers" to "failed during chain verification" -
// further in, still short. 4096 is the next step and is still generous for handlers that parse a
// small form and print a status page. Raise it again if a portal handler ever does real work.
// build_flags_async =
#define CONFIG_ASYNC_TCP_STACK_SIZE 4096

// build_flags =
//     ${common.build_flags_frugaliot}
//     ${common.build_flags_main}
//     ${common.build_flags_library}
//     ${common.build_flags_lvd}
//     ${common.build_flags_map}
//     ${common.build_flags_async}

// platform_esp32 = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

// [env]
// src_dir = . means "the project's sources are at the top of the repo", which is what makes the
// same directory open in the Arduino IDE. But it also means PlatformIO would compile EVERY .cpp
// below here as project source - including, through the lib/Frugal-IoT symlink, the library's own
// examples and their downloaded dependencies. So say explicitly what is ours.
// Arduino IDE needs no equivalent: it ignores every subdirectory except src/.
// ota-stage/ is where scripts/release.zsh --build stages its builds, each a tree of symlinks back to
// these same sources - so without excluding it, every file would be compiled twice.
// build_src_filter = +<*> -<lib/> -<data/> -<scripts/> -<.pio/> -<docs/> -<ota-stage/>
// monitor_speed = 460800 ; If not 460800 then also change in main.cpp: frugal_iot.startSerial(newspeed, 5000);
// upload_speed = 460800
// framework = arduino
// board_build.filesystem = littlefs ; Use LittleFS instead of SPIFFS
// lib_compat_mode = strict
// lib_deps = ${common.lib_deps}
// lib_ldf_mode = chain

// ==== FF-ESP32-OpenMPPT =============================================
// The solar charge controller board OSPIT runs on - a plain ESP32. Pin assignments below are
// OSPIT's own, read out of its Lua - see OSPIT_COMPARISON.md for where each comes from.
//
// NOTE the display here is the I2C SSD1306, NOT the SSD1327 SPI panel that examples/all builds for
// this board. The SSD1327 needs dc=16 and rst=17, which are the very UEXT pins the RS485 probes
// use - you get the display or the probes, not both.

// ===== [env:ff_openmppt] -> ARDUINO_ESP32_DEV
#if defined(ARDUINO_ESP32_DEV) || defined(FF_OPENMPPT)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = esp32dev ; defines ARDUINO_ESP32_DEV
// board_build.partitions = min_spiffs.csv
// build_flags =
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "ff_openmppt"
    // --- irrigation hardware ---
#define IRRIGATION_VALVE1_PIN 26
#define IRRIGATION_VALVE2_PIN 27
#define IRRIGATION_VALVE3_PIN 12
    // Pin 14 can be a pump OR a load switch, not both - see OSPIT_COMPARISON.md. The pump role is
    // chosen here because it exercises the pump path. To swap, comment out IRRIGATION_PUMP_PIN and
    // uncomment IRRIGATION_LOAD_PIN.
#define IRRIGATION_PUMP_PIN 14
// #define IRRIGATION_LOAD_PIN 14
    // A USB supply on pin 12 - the SAME PIN as valve 3, so define one or the other. If you enable
    // this, remove IRRIGATION_VALVE3_PIN above and drop sector 3 from the sketch.
// #define IRRIGATION_USB_PIN 12
    // The tank gauge. mp2.lua's header comment calls GPIO32 a temperature sense input, but
    // irrigation.lua reads it as the tank - question 7 in HARDWARE-QUESTIONS.md settles it. If it
    // turns out to be the temperature input, comment this out and no tank code is compiled.
#define SENSOR_TANK_PIN 32
    // --- RS485 soil probes. Slave ids are set in the .ino and start at 2: address 1 is the
    // factory default and has to stay meaning "not yet provisioned" - see sensor/soilmodbus.h
#define SENSOR_SOILMODBUS_WANT
#define SENSOR_SOILMODBUS_AUTOPROVISION
#define SYSTEM_RS485_RX_PIN 16
#define SYSTEM_RS485_TX_PIN 17
#define SYSTEM_RS485_UART Serial2
    // --- charge controller instrumentation (P5.1 - measurement only, nothing is driven) ---
    // Solar panel voltage. 1k/27k divider is the 0.035714 ratio in mp2.lua's Vinmeasure(), so 28.
#define MPPT_PANEL_PIN 34
#define MPPT_PANEL_DIVIDER 28
    // The series Schottky D6 drops about 300mV, so the panel is that much higher than the pin says.
    // SET THIS TO 0 if D6 has been replaced by a wire on your board - question 2 in
    // HARDWARE-QUESTIONS.md tells the tester how to look.
#define MPPT_PANEL_DIODE_MV 300
    // Up to three DS18B20 probes share this pin - air, battery and board temperature. They are told
    // apart by the id burned into each probe, so which is which survives unplugging them.
#define MPPT_ONEWIRE_PIN 2
    // The OTHER way this board can measure its own heat: two diodes read as an analog voltage.
    // LEFT OFF DELIBERATELY - we believe the DS18B20 above does this job, and turning both on would
    // give two different answers to the same question. Question 4 in HARDWARE-QUESTIONS.md asks
    // the tester to look for the diodes; uncomment if they are there and the DS18B20 is not.
// #define SENSOR_HEATSINK_PIN 35
    // --- solar charge control (P5.2 - set by hand, nothing tracks yet) ---
    // DAC channel 1. Channel 2 is GPIO26, which this board uses as valve 1, so there is only one.
#define MPPT_DAC_PIN 25
    // Which panel-voltage range the charge circuit can ask for. With neither of these set nor a
    // CONTROL_MPPT_BOARD_FF_1_0 / _1_1 flag, the v1.2 figures are used - the most recent board, so
    // a new one needs nothing here. Question 1 in HARDWARE-QUESTIONS.md asks which board it is.
// #define CONTROL_MPPT_BOARD_FF_1_0
// #define CONTROL_MPPT_BOARD_FF_1_1
// #define CONTROL_MPPT_VMPP_MIN 12.86 // give BOTH of these or NEITHER - control_mppt.h #errors
// #define CONTROL_MPPT_VMPP_MAX 25.15
    // --- battery, for the low-voltage interlocks ---
    // A reading below this is treated as a broken sensor rather than a flat battery, so it can
    // never trigger the low-voltage sleep. 9V is under any usable 12V battery and over any
    // plausible garbage; the library's 2500 default is sized for a single lithium cell.
#define SYSTEM_POWER_BAD_READING_MV 9000
    // Low-voltage deep sleep - OSPIT's low_voltage_sleep_enabled. DELIBERATELY NOT ENABLED YET:
    // under 11.9V the node would deep sleep five minutes at a time, but we do not know what the
    // load switch (pin 14) and the DAC (pin 25) do while the ESP32 sleeps, so it could make things
    // worse. See OSPIT_COMPARISON.md, docs/sleep-test.md and question 10 in HARDWARE-QUESTIONS.md.
// #define SYSTEM_POWER_LOW_MV 11900
// #define SYSTEM_POWER_LOW_MS 300000
#define SENSOR_BATTERY_PIN 33
    // OSPIT's 1k/15k divider, a factor of 16. It uses only about a quarter of the ADC's range;
    // 3k3/15k (factor 5.546) is better on new hardware - see OSPIT_COMPARISON.md.
#define SENSOR_BATTERY_VOLTAGE_DIVIDER 16
    // --- display ---
    // This board has no OLED in its board definition, so the chip, the bus and the panel size all
    // have to be stated explicitly - actuator/oled.h #errors rather than guessing any of them.
#define ACTUATOR_OLED_WANT
#define ACTUATOR_OLED_IS_SSD1306
#define OLED_WIRE Wire
#define OLED_SDA 21
#define OLED_SCL 22
#define OLED_RST_X -1
#define ACTUATOR_OLED_WIDTH 128
#define ACTUATOR_OLED_HEIGHT 64
// lib_deps =
//     ${common.lib_deps_oled}

// ==== Lolin S2 Mini =================================================
// The same application with no charge-controller hardware. Pin choices follow
// https://github.com/mitra42/frugal-iot/wiki/Pin-usage-on-various-dev-boards#lolin-s2-mini :
// every ADC1 pin (GPIO1-10) is left free for analog, and the digital traffic is put on ADC2 pins
// (GPIO11-20), which are unusable for analog anyway once WiFi is up.
#endif // ARDUINO_ESP32_DEV

// ===== [env:s2_mini] -> ARDUINO_LOLIN_S2_MINI
#if defined(ARDUINO_LOLIN_S2_MINI) || defined(S2_MINI)
#define FRUGAL_IOT_BOARD_CONFIGURED
// platform = ${common.platform_esp32}
// board = lolin_s2_mini ; defines ARDUINO_LOLIN_S2_MINI
// board_build.partitions = min_spiffs.csv
// build_flags =
//     ${common.build_flags}
#define SYSTEM_OTA_SUFFIX "s2_mini"
    // --- irrigation hardware ---
#define IRRIGATION_VALVE1_PIN 10
#define IRRIGATION_VALVE2_PIN 13
#define IRRIGATION_VALVE3_PIN 14
    // Unlike the FF board this one has pins to spare, so it carries both roles separately - which
    // also means this env is the one that compiles both paths.
#define IRRIGATION_PUMP_PIN 38 // digital-only pin; examples/agri already drives 38 as an output
#define IRRIGATION_LOAD_PIN 40 // digital-only, from the wiki's 37-44 set (37 and 39 are UART0)
#define SENSOR_TANK_PIN 6 // ADC1_CH5
    // --- RS485 soil probes - slave ids from 2, see the note in the FF env ---
#define SENSOR_SOILMODBUS_WANT
#define SENSOR_SOILMODBUS_AUTOPROVISION
#define SYSTEM_RS485_RX_PIN 16
#define SYSTEM_RS485_TX_PIN 18
#define SYSTEM_RS485_UART Serial1 // The S2 has Serial0 and Serial1 only - there is no Serial2
#define SENSOR_BATTERY_PIN 8 // ADC1_CH7 comment out if testing on board with no resistor divider fitted or will auto-deep-sleep
#define SENSOR_BATTERY_VOLTAGE_DIVIDER 6.641 // 220k/39k
#define SYSTEM_POWER_BAD_READING_MV 9000
 #endif // ARDUINO_LOLIN_S2_MINI

#ifndef FRUGAL_IOT_BOARD_CONFIGURED
  #error "This board has no settings in platform.h. Under Tools > Board, select one of the boards this example supports, or add a section for yours to its platformio.ini and re-run scripts/generate_platform_h.py. Supported here: ESP32 Dev Module / LOLIN S2 Mini"
#endif

#endif // PLATFORM_H
